#!/bin/sh
### General options
### -- specify queue -- 
#BSUB -q hpc
### -- set the job Name --
#BSUB -J bioreader_Eukar
### -- ask for number of cores -- 
#BSUB -n 10
### -- specify that the cores must be on the same host -- 
#BSUB -R "span[hosts=1]"
### -- specify that we need XGB of memory per core/slot -- 
#BSUB -R "rusage[mem=7GB]"
### -- specify that we want the job to get killed if it exceeds X GB per core/slot -- 
#BSUB -M 7.35GB
### -- set walltime limit: hh:mm -- 
#BSUB -W 12:00
### -- set the email address -- 
# please uncomment the following line and put in your e-mail address,
# if you want to receive e-mail notifications on a non-default address
#BSUB -u s193518@dtu.dk
### -- send notification at start -- 
#BSUB -B
### -- send notification at completion -- 
#BSUB -N 
### -- Specify the output and error file. %J is the job-id -- 
### -- -o and -e mean append, -oo and -eo mean overwrite -- 
#BSUB -e log/bioreader_%J.err
#BSUB -o log/bioreader_%J.out
module load R/4.3.1-mkl2023update1
export R_BATCH_OPTIONS="--no-save"
mkdir -p log/
mkdir -p time/
/usr/bin/time -v -o time/bioreader.time Rscript src/R/main_PRIAT.R -a Eukar -p --hpc

